name: Test Project
on: [push]

jobs:
  test:
    runs-on: macos-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Install NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install React Native
        run:  npx react-native@latest init AwesomeRNProject --install-pods
      - name: Install dependencies
        run: npm ci
      - name: Run tests
        run: npm test
